import urllib.parse

import pandas as pd
import streamlit as st

from violation_detection import get_challan_history, mark_notified
from config import DEFAULT_COUNTRY_CODE

st.set_page_config(page_title="Challan History", page_icon="📋", layout="wide")

st.markdown("## 📋 Challan History")
st.caption("Every challan generated by the system, most recent first.")

rows = get_challan_history()

if not rows:
    st.info("No challans have been issued yet. Generate one from the home page.")
    st.stop()

df = pd.DataFrame(rows, columns=[
    "ID", "Driver Name", "Vehicle Reg", "Vehicle Type", "Violation",
    "Fine (₹)", "Mobile", "Date", "Notified",
])
df["Notified"] = df["Notified"].map({1: "✅ Yes", 0: "❌ No", None: "❌ No"})

col1, col2, col3 = st.columns(3)
col1.metric("Total Challans", len(df))
col2.metric("Total Fines Collected", f"₹ {int(df['Fine (₹)'].sum())}")
col3.metric("Pending Notification", int((df["Notified"] == "❌ No").sum()))

st.divider()

violation_filter = st.multiselect(
    "Filter by violation",
    options=sorted(df["Violation"].unique()),
    default=[],
)
filtered_df = df[df["Violation"].isin(violation_filter)] if violation_filter else df

st.dataframe(filtered_df, use_container_width=True, hide_index=True)

st.divider()
st.markdown("### 📱 Re-send a WhatsApp Notification")

pending = [r for r in rows if r[5] and str(r[5]).strip()]
if pending:
    options = {f"#{r[0]} — {r[1] or 'Unknown'} ({r[2]}) — {r[4]}": r for r in pending}
    choice = st.selectbox("Select a challan", list(options.keys()))
    selected = options[choice]

    challan_id, driver_name, vehicle_reg, vehicle_type, violation, fine, mobile, date, notified = selected

    phone = "".join(ch for ch in str(mobile) if ch.isdigit())
    whatsapp_number = DEFAULT_COUNTRY_CODE + phone if len(phone) == 10 else phone

    whatsapp_message = f"""TRAFFIC CHALLAN ALERT

Dear {driver_name or 'Vehicle Owner'},

A traffic violation has been detected for your vehicle.

Vehicle Number: {vehicle_reg}
Vehicle Type: {vehicle_type or '-'}

Violation: {violation}
Fine Amount: ₹{fine}

Please pay the challan according to the applicable traffic rules.

Thank you.
Traffic Challan System"""

    encoded_message = urllib.parse.quote(whatsapp_message)
    whatsapp_url = f"https://wa.me/{whatsapp_number}?text={encoded_message}"

    st.code(whatsapp_message, language=None)
    st.link_button("📱 SEND ON WHATSAPP", whatsapp_url, use_container_width=True, type="primary")

    if st.button("✅ Mark as notified", use_container_width=True):
        mark_notified(challan_id)
        st.success("Marked as notified.")
        st.rerun()
else:
    st.info("No challans with a mobile number on file yet.")
